Limpeza e tratamento da tabela TipoCrime.

In [3]:
#chamando biblioteca
import pandas as pd

#lendo csv
tipoCrime = pd.read_csv('C:/Users/PICHAU/Downloads/iucr_lista.csv', sep=';', encoding='utf-8')

#criando dataframe
tipoCrime = pd.DataFrame(tipoCrime)

tipoCrime

,IUCR,PRIMARY DESCRIPTION,SECONDARY DESCRIPTION,INDEX CODE,ACTIVE,FBI_code
0,110,HOMICIDE,FIRST DEGREE MURDER,I,True,01A
1,130,HOMICIDE,SECOND DEGREE MURDER,I,True,01A
2,141,HOMICIDE,INVOLUNTARY MANSLAUGHTER,N,True,01B
3,142,HOMICIDE,RECKLESS HOMICIDE,N,True,01B
4,261,CRIMINAL SEXUAL ASSAULT,AGGRAVATED - HANDGUN,I,True,2
...,...,...,...,...,...,...
405,5121,OTHER OFFENSE,ARSONIST - ANNUAL REGISTRATION,N,True,NaN
406,5122,OTHER OFFENSE,ARSONIST - FAIL TO REGISTER NEW ADDRESS,N,True,NaN
407,5130,OTHER OFFENSE,VIOLENT OFFENDER - DUTY TO REGISTER,N,True,NaN
408,5131,OTHER OFFENSE,VIOLENT OFFENDER - ANNUAL REGISTRATION,N,True,NaN
409,5132,OTHER OFFENSE,VIOLENT OFFENDER - FAIL TO REGISTER NEW ADDRESS,N,True,NaN

In [4]:
#apagando colunas desnecessÃ¡rias
del tipoCrime['ACTIVE']
del tipoCrime['INDEX CODE']
tipoCrime

,IUCR,PRIMARY DESCRIPTION,SECONDARY DESCRIPTION,FBI_code
0,110,HOMICIDE,FIRST DEGREE MURDER,01A
1,130,HOMICIDE,SECOND DEGREE MURDER,01A
2,141,HOMICIDE,INVOLUNTARY MANSLAUGHTER,01B
3,142,HOMICIDE,RECKLESS HOMICIDE,01B
4,261,CRIMINAL SEXUAL ASSAULT,AGGRAVATED - HANDGUN,2
...,...,...,...,...
405,5121,OTHER OFFENSE,ARSONIST - ANNUAL REGISTRATION,NaN
406,5122,OTHER OFFENSE,ARSONIST - FAIL TO REGISTER NEW ADDRESS,NaN
407,5130,OTHER OFFENSE,VIOLENT OFFENDER - DUTY TO REGISTER,NaN
408,5131,OTHER OFFENSE,VIOLENT OFFENDER - ANNUAL REGISTRATION,NaN
409,5132,OTHER OFFENSE,VIOLENT OFFENDER - FAIL TO REGISTER NEW ADDRESS,NaN

In [5]:
#apagando linhas com valores nulos na coluna FBI_code
tipoCrime.dropna(subset=['FBI_code'], inplace=True)

tipoCrime

,IUCR,PRIMARY DESCRIPTION,SECONDARY DESCRIPTION,FBI_code
0,110,HOMICIDE,FIRST DEGREE MURDER,01A
1,130,HOMICIDE,SECOND DEGREE MURDER,01A
2,141,HOMICIDE,INVOLUNTARY MANSLAUGHTER,01B
3,142,HOMICIDE,RECKLESS HOMICIDE,01B
4,261,CRIMINAL SEXUAL ASSAULT,AGGRAVATED - HANDGUN,2
...,...,...,...,...
396,501A,OTHER OFFENSE,ANIMAL ABUSE / NEGLECT,26
397,501H,OTHER OFFENSE,HAZARDOUS MATERIALS VIOLATION,26
398,502P,OTHER OFFENSE,FALSE / STOLEN / ALTERED TRP,26
399,502R,OTHER OFFENSE,VEHICLE TITLE / REGISTRATION OFFENSE,26
400,502T,OTHER OFFENSE,TAMPER WITH MOTOR VEHICLE,26

In [6]:
#renomeando as colunas
tipoCrime.rename(columns=
 {"PRIMARY DESCRIPTION": "CategoriaCrime",
  "SECONDARY DESCRIPTION": "DescricaoCrime",
  "FBI_code": "CodigoFBI"},
inplace=True)

tipoCrime

,IUCR,CategoriaCrime,DescricaoCrime,CodigoFBI
0,110,HOMICIDE,FIRST DEGREE MURDER,01A
1,130,HOMICIDE,SECOND DEGREE MURDER,01A
2,141,HOMICIDE,INVOLUNTARY MANSLAUGHTER,01B
3,142,HOMICIDE,RECKLESS HOMICIDE,01B
4,261,CRIMINAL SEXUAL ASSAULT,AGGRAVATED - HANDGUN,2
...,...,...,...,...
396,501A,OTHER OFFENSE,ANIMAL ABUSE / NEGLECT,26
397,501H,OTHER OFFENSE,HAZARDOUS MATERIALS VIOLATION,26
398,502P,OTHER OFFENSE,FALSE / STOLEN / ALTERED TRP,26
399,502R,OTHER OFFENSE,VEHICLE TITLE / REGISTRATION OFFENSE,26
400,502T,OTHER OFFENSE,TAMPER WITH MOTOR VEHICLE,26

In [7]:
#gerando csv
tipoCrime.to_csv('tipoCrime.csv')